name: Deploy clicker to production

on:
  push:
    branches:
      - master
    paths:
      - "clicker/**"

jobs:
  deploy-clicker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: schneefux.xyz
          app-name: clicker.brawltime.ninja
          git-push-flags: "--force"
